@ChatRoomAPI_HostAddress = chathubgame-csahbkcqa2asefgy.centralus-01.azurewebsites.net
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJnYXlAZW1haWwuY29tIiwidW5pcXVlX25hbWUiOiJnYXlib3kiLCJqdGkiOiJjMDc4ZWZjOC0zMThjLTQwNWEtYTFkMC1mNWE1NmM0YmIwNTIiLCJleHAiOjE3Nzk5Mzc4NDQsImlzcyI6IkNoYXRBcGkiLCJhdWQiOiJDaGF0Q2xpZW50In0.5QDRw3S0acKMeXazCcZWE-1IqjTRCNnEgS20Bmi2rS8
GET {{ChatRoomAPI_HostAddress}}
Accept: application/json

### Register
POST {{ChatRoomAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "username": "gayboy",
    "email": "gay@email.com",
    "password": "gayboy"
}
###
POST {{ChatRoomAPI_HostAddress}}/api/auth/register
Content-Type: application/json

{
    "username": "admin",
    "email": "admin",
    "password": "admin"
}

### Login
POST {{ChatRoomAPI_HostAddress}}/api/auth/login
Content-Type: application/json

{
    "email": "gay@email.com",
    "password": "gayboy"
}

### Get Rooms
GET {{ChatRoomAPI_HostAddress}}/api/room

### Create Room
POST {{ChatRoomAPI_HostAddress}}/api/room
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Lobby"
}

### Get Room Messages
GET {{ChatRoomAPI_HostAddress}}/api/room/1/messages
Authorization: Bearer {{token}}